<h4>System report for submited contact for User</h4>
<p>Dear {{$name}}</p>
<p>System has received your orders, we will read and contact you later if needed.</p>
<p>Thanks for using your service.</p>
<p>From:System.</p><p>This message was generated by SYSTEM. DO NOT REPLY</p>
